# Generated by Django 5.0.14 on 2025-07-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentprofile_graduation_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(max_length=200, blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(max_length=100, blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, blank=True),
        ),
    ]
