# Generated by Django 5.0.14 on 2025-07-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20250705_1636'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE students_studentprofile ALTER COLUMN university DROP NOT NULL;",
            reverse_sql="ALTER TABLE students_studentprofile ALTER COLUMN university SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE students_studentprofile ALTER COLUMN major DROP NOT NULL;",
            reverse_sql="ALTER TABLE students_studentprofile ALTER COLUMN major SET NOT NULL;"
        ),
        migrations.RunSQL(
            "ALTER TABLE students_studentprofile ALTER COLUMN student_id DROP NOT NULL;",
            reverse_sql="ALTER TABLE students_studentprofile ALTER COLUMN student_id SET NOT NULL;"
        ),
    ]
