# Generated by Django 5.0.14 on 2025-08-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Academic Exam',
                'verbose_name_plural': 'Academic Exams',
            },
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AcademicExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField()),
                ('step', models.IntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.academicexam')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('exam', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('taken_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='students.academicexam')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='students.academicexamsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='students.studentprofile')),
            ],
            options={
                'ordering': ['exam_id', 'section_id'],
                'unique_together': {('student', 'section')},
            },
        ),
    ]
