# Generated by Django 5.0.14 on 2025-08-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_academicexam_alter_sociallink_id_academicexamsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicexamsection',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='academicexamsection',
            name='min_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='academicexamsection',
            name='step',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='studentexamscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
