# Generated by Django 5.0.14 on 2025-09-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_academicexamsection_max_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_preferences', to='students.preference')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='students.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'preference')},
            },
        ),
    ]
