# Generated by Django 5.0.14 on 2025-09-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='application_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief bio or mission statement'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='founded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='weekly_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('university', 'University'), ('company', 'Company'), ('nonprofit', 'Non-profit'), ('government', 'Government'), ('research', 'Research Institution'), ('startup', 'Startup'), ('foundation', 'Foundation'), ('ngo', 'NGO')], max_length=20),
        ),
    ]
