# Generated by Django 5.0.14 on 2025-07-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('opportunities', '0002_opportunityquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='application_answers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunityquestion')),
            ],
            options={
                'unique_together': {('application', 'question')},
            },
        ),
    ]
