# Generated by Django 5.0.14 on 2025-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reference1_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='reference1_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='reference1_relationship',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='relevant_experience',
            field=models.TextField(blank=True),
        ),
    ]
