# Generated by Django 5.0.14 on 2025-07-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='application',
            name='relevant_experience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference1_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference1_contact',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reference1_relationship',
        ),
    ]
