# Generated by Django 5.0.14 on 2025-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uz', 'O‘zbekcha')], default='en', max_length=5),
        ),
    ]
