# Generated by Django 5.0.14 on 2025-07-11 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('email', 'Email'), ('url', 'URL'), ('date', 'Date'), ('file', 'File Upload'), ('select', 'Multiple Choice'), ('checkbox', 'Checkbox')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, help_text='Options for select/checkbox questions', null=True)),
                ('max_length', models.IntegerField(blank=True, help_text='Maximum length for text fields', null=True)),
                ('min_length', models.IntegerField(blank=True, help_text='Minimum length for text fields', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_questions', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
