# Generated by Django 5.0.14 on 2025-07-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity_covers/'),
        ),
    ]
