# Generated by Django 5.0.14 on 2025-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_opportunity_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
