# Generated by Django 5.0.14 on 2025-09-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_opportunity_age_max_opportunity_age_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('volunteer', 'Volunteer'), ('competition', 'Competition'), ('scholarship', 'Scholarship'), ('job', 'Job'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('event', 'Event')], max_length=20),
        ),
    ]
