# Generated by Django 5.0.14 on 2025-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_alter_opportunity_opportunity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('conference', 'Conference'), ('volunteer', 'Volunteer'), ('international_events', 'International events'), ('scholarship', 'Scholarship'), ('camp', 'Camp'), ('grant', 'Grant'), ('mentoring', 'Mentoring'), ('academic_program', 'Academic Program')], max_length=20),
        ),
    ]
