# Generated by Django 5.0.14 on 2025-09-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_opportunity_result_announcement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='benefits',
            field=models.TextField(blank=True, help_text='Additional benefits and perks offered'),
        ),
        migrations.CreateModel(
            name='OpportunityProfileRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('basic_info', 'Basic Information'), ('education', 'Education'), ('experience', 'Experience'), ('skills', 'Skills'), ('projects', 'Projects'), ('languages', 'Languages'), ('certifications', 'Certifications'), ('awards', 'Awards'), ('extracurricular', 'Extracurricular Activities'), ('personal_statement', 'Personal Statement'), ('portfolio', 'Portfolio'), ('resume', 'Resume'), ('linkedin', 'LinkedIn Profile'), ('github', 'GitHub Profile'), ('website', 'Personal Website')], max_length=50)),
                ('requirement_level', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='required', max_length=20)),
                ('custom_message', models.TextField(blank=True, help_text='Custom message to show when this requirement is not met')),
                ('minimum_items', models.PositiveIntegerField(default=1, help_text='Minimum number of items required in this section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_requirements', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['requirement_level', 'section'],
                'unique_together': {('opportunity', 'section')},
            },
        ),
    ]
