# Generated by Django 5.0.14 on 2025-09-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_alter_opportunity_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='application_instructions',
            field=models.TextField(blank=True, help_text='Guidelines and instructions for applicants'),
        ),
    ]
